### ISSUE TITLE
DOES IT WORK WITH EMOJI?

### ISSUE THREAD

**Issue by JayFriesen** [brantb/hubot-loudbot#3]
I THINK I SHOULD BE ABLE TO SHOUT WITH :cake:

**Comment by coryallegory** [comment]
It should work with emoji as long as letters are 90% of the message or more.

**Comment by coryallegory** [comment]
Added example string as test case for emoji
https://github.com/brantb/hubot-loudbot/pull/10

**Comment by brantb** [comment]
👍
