### ISSUE TITLE
Don't save louds that start with the bot name

### ISSUE THREAD

**Issue by brantb** [brantb/hubot-loudbot#7]
People who yell at hubot should get a response but the text probably shouldn't be added to the corpus.

**Comment by coryallegory** [comment]
Addressed by https://github.com/brantb/hubot-loudbot/pull/9 .

**Comment by brantb** [comment]
After living with this behavior for a year I've decided that it's kind of hilarious when hubot yells at itself, so I'm going to leave this one unmerged.
